### ISSUE TITLE
Https support?

### ISSUE THREAD

**Issue by saahilcc** [redfin/mobbage#1]
Saahils-MacBook-Pro:Simple-Web-Server-master DirtyRa$ mobbage https://127.0.0.1:8080 -n 500000 -w 1 -p -i
Starting mobbage with 1 worker.
Results:                                                                       
    Total time:        00:00:04
    Requests:          1441
    Successes:         0
    Errors:            1441
    Availability       0.00%
    Minimum time:      0ms
    Average time:      0ms
    Maximum time:      0ms
    Minimum size:      0.0B
    Average size:      0.0B
    Maximum size:      0.0B
    Total data:        0.0B
    Average data rate: 0.0B/s
    Concurrency:       324.63

    Results by return code
        400:         1441

**Comment by davidalber** [comment]
Hi, @Ninja-koto. I'm sorry that there was no response to this for a year; there's been a lapse of leadership in this repository.

I'm unable to repro this issue. In case you are still out there and remember anything about this, I'll leave the ticket open to see if you have more information.

### Attempt to Repro
#### Site with Valid Certificate
Note: I omitted the `-i` argument since it's not needed for this domain.
```
$ mobbage https://www.redfin.com -n 10 -w 1 -p
Starting mobbage with 1 worker.
Results:
    Total time:        00:00:02
    Requests:          10
    Successes:         10
    Errors:            0
    Availability       100.00%
    Minimum time:      31ms
    Average time:      35ms
    Maximum time:      39ms
    Minimum size:      106.5KB
    Average size:      106.8KB
    Maximum size:      107.6KB
    Total data:        1.1MB
    Average data rate: 374.2KB/s
    Concurrency:       3.50

    Results by return code
        200:           10
```

#### Site with Invalid Certificate
For this test, I spun up a service and fronted it with an NGINX instance with a self-signed certificate. Steps to repro this:
1. `$ git clone git@github.com:pinterest/snappass.git`
1. `$ cd snappass/`
1. `$ docker-compose up -d` (Now I have a service running on port 5000 reachable via HTTP.)
1. (In some other directory...)`$ git@github.com:davidalber/self-signed-docker-nginx-reverse-proxy.git`
1. `$ cd self-signed-docker-nginx-reverse-proxy/`
1. `./mkproxy up -p 5000` (Now the service is reachable via https://localhost.)

And the test:
```
$ mobbage https://localhost -n 10 -w 1 -p -i
Starting mobbage with 1 worker.
Results:
    Total time:        00:00:00
    Requests:          10
    Successes:         10
    Errors:            0
    Availability       100.00%
    Minimum time:      24ms
    Average time:      27ms
    Maximum time:      32ms
    Minimum size:      2.1KB
    Average size:      2.1KB
    Maximum size:      2.1KB
    Total data:        20.9KB
    Average data rate: 31.2KB/s
    Concurrency:       14.96

    Results by return code
        200:           10
```

And just to make sure it's an invalid certificate:
```
$ mobbage https://localhost -n 10 -w 1 -p
Starting mobbage with 1 worker.
Results:
    Total time:        00:00:00
    Requests:          10
    Successes:         0
    Errors:            10
    Availability       0.00%
    Minimum time:      0ms
    Average time:      0ms
    Maximum time:      0ms
    Minimum size:      0.0B
    Average size:      0.0B
    Maximum size:      0.0B
    Total data:        0.0B
    Average data rate: 0.0B/s
    Concurrency:       21.52

    Results by return code
        400:           10
```

Is there anything else about the issue that you can share? Are you certain https://127.0.0.1:8080/ returned 200 for other requests?

**Comment by davidalber** [comment]
Since I am unable to repro this, I am closing this as no repro. If this happens again or there's more information available about the issue, please reopen.
